### PR TITLE
Fix for specified size of additional disks on Instance being ignored

### PR DESCRIPTION
**Pull request by M-Schiefer**
Fix for https://github.com/GoogleCloudPlatform/elcarro-oracle-operator/issues/371

### CODE REVIEW

**Comment by akinfermo** [comment]
Hi @M-Schiefer , can you please sign the CLA https://cla.developers.google.com/? It's necessary for us to merge your contribution.

**Comment by M-Schiefer** [comment]
Hey @akinfermo, I fixed my CLA a while ago, but the operator-oss-presubmit failed.
Is there anything I still need to do here?

Thank you!

**Review by akinfermo — APPROVED** [review]
LGTM

**Pull request merged**
