### PR TITLE
ConfigAgent: move `BounceDatabase(`

### PR DESCRIPTION
**Pull request by ZachMorek**
Change-Id: I3955b90fc8a60462325348ad3a4d99a06765cc0d

### CODE REVIEW

**Review by haohu-hh — APPROVED** [review]
LGTM

**Comment by ZachMorek** [comment]
Looked over the PR while rebasing and noticed that the `req` struct had another arg and should be used as a full struct to keep the args structured.

Also reviewed all previously merged PRs to confirm that this same oversight didn't occur.

**Review by aravindous — APPROVED** [review]
LGTM

**Pull request merged**
